# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  password: brian
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_database_development

 
test:
  <<: *default
  database: auth_database_test


production:
  <<: *default
  database: auth_database_production
  username: auth_database
  password: <%= ENV["auth_database_DATABASE_PASSWORD"] %>
